CREATE TABLE GENERO (
	CD_GENERO INTEGER NOT NULL PRIMARY KEY,
	NM_GENERO VARCHAR(100) NOT NULL
);

CREATE TABLE AUTOR (
	CD_AUTOR INTEGER NOT NULL PRIMARY KEY,
	NM_AUTOR VARCHAR(100) NOT NULL
);

CREATE TABLE EDITORA (
	CD_EDITORA INTEGER NOT NULL PRIMARY KEY,
	NM_EDITORA VARCHAR(100) NOT NULL
);

CREATE TABLE LIVRO (
	CD_LIVRO INTEGER NOT NULL PRIMARY KEY,
	NM_LIVRO VARCHAR(200) NOT NULL,
	DS_RESUMO VARCHAR(500),
	NR_ISBN VARCHAR(10) NOT NULL,
	NR_ANOPUBLICACAO INTEGER NOT NULL,
	CD_EDITORA INTEGER NOT NULL,
	CD_AUTOR INTEGER NOT NULL,
	CD_GENERO INTEGER NOT NULL,
	FOREIGN KEY(CD_EDITORA) REFERENCES EDITORA(CD_EDITORA),
	FOREIGN KEY(CD_AUTOR) REFERENCES AUTOR(CD_AUTOR),
	FOREIGN KEY(CD_GENERO) REFERENCES GENERO(CD_GENERO)
);

CREATE TABLE EXEMPLAR (
	CD_EXEMPLAR INTEGER NOT NULL PRIMARY KEY,
	NR_EXEMPLAR INTEGER NOT NULL,
	CD_LIVRO INTEGER NOT NULL,
	FOREIGN KEY(CD_LIVRO) REFERENCES LIVRO(CD_LIVRO)
);

CREATE TABLE LOCALIZACAOLIVRO (
	CD_EXEMPLAR INTEGER NOT NULL,
	CD_LIVRO INTEGER NOT NULL,
	NR_FILEIRA INTEGER NOT NULL,
	DS_LADO VARCHAR(10) NOT NULL,
	NR_ANDAR INTEGER NOT NULL,
	FOREIGN KEY(CD_EXEMPLAR) REFERENCES EXEMPLAR(CD_EXEMPLAR),
	FOREIGN KEY(CD_LIVRO) REFERENCES LIVRO(CD_LIVRO)
);
