SELECT l.NM_LIVRO,
a.NM_AUTOR,
ed.NM_EDITORA
FROM LIVRO l

FULL JOIN AUTOR a ON
l.CD_AUTOR = a.CD_AUTOR

FULL JOIN EDITORA ed ON
l.CD_EDITORA = ed.CD_EDITORA

WHERE ed.CD_EDITORA = 4
OR a.CD_AUTOR = 2

ORDER BY ed.NM_EDITORA;