SELECT l.NM_LIVRO,
a.NM_AUTOR,
g.NM_GENERO,
ed.NM_EDITORA
FROM LIVRO l

FULL JOIN AUTOR a ON
l.CD_AUTOR = a.CD_AUTOR

FULL JOIN GENERO g ON
l.CD_GENERO = g.CD_GENERO

FULL JOIN EDITORA ed ON
l.CD_EDITORA = ed.CD_EDITORA;