SELECT l.NM_LIVRO,
ed.NM_EDITORA,
a.NM_AUTOR
FROM LIVRO l

INNER JOIN EDITORA ed ON
l.CD_EDITORA = ed.CD_EDITORA

INNER JOIN AUTOR a ON
l.CD_AUTOR = a.CD_AUTOR

INNER JOIN GENERO g ON
l.CD_GENERO = g.CD_GENERO

WHERE g.NM_GENERO LIKE 'R%';